### ISSUE TITLE
EchoEvent

### ISSUE THREAD

**Issue by HwangWonYo** [HwangWonYo/naver_talk_sdk#1]
Handling EchoEvent is quite difficult.
Please comment any good idea to handle echo event.
See More Info about [EchoEvent](https://github.com/navertalk/chatbot-api#echo-%EC%9D%B4%EB%B2%A4%ED%8A%B8)

**Comment by lesimor** [comment]
@HwangWonYo ㅎㅇ

**Comment by HwangWonYo** [comment]
#11
