### ISSUE TITLE
안녕하세요, IoT pet home system 팀입니다

### ISSUE THREAD

**Issue by kuj0210** [HwangWonYo/naver_talk_sdk#21]
안녕하세요 잘지내고계신가요?  IoT pet home system 팀 김우진입니다.
개발하시는데 방해가 될까 싶어 많이 망설였는데 저번 미팅 때 작년 FEST에서도 프로젝트를 함께 진행한 경우가 있다 들어서 생각나서 연락드립니다.

혹시 저희랑 저희 프로젝트 같이 진행하실 생각있으신지 여쭤봅니다.

부담럽지 않은 선에서 같이 진행하면 서로 긍정적일 것이라 생각하고. 만약 저희 제안을 좋게 생각하신다면 저희쪽에 이슈부탁드립니다. 

같이 진행을 하더라도 본 naver_talk_sdk 쪽 이슈가 발생한다면, 그쪽을 우선으로 하시는 쪽으로 했으면 하고 저희도 협력가능하다면 도움드리고 싶습니다. 

이슈기다리겠습니다.

**Comment by HwangWonYo** [comment]
이 프로젝트 Issue에서는 nta 관련 이슈만 남기는게 좋을것 같아요! 메일로 연락하죠
